import { addMinutes, subMinutes, format } from 'date-fns'

const now = new Date()

// ─── USERS ───────────────────────────────────────────────────────────────────
export const MOCK_USERS = {
  patient1: {
    id: 'patient-user-1',
    patient_id: 'patient-1',
    email: 'sarah.johnson@email.com',
    role: 'patient',
    full_name: 'Sarah Johnson',
    phone: '+1 (555) 234-5678',
    avatar_url: null,
    created_at: '2024-01-15T10:00:00Z',
  },
  doctor1: {
    id: 'doctor-user-1',
    doctor_id: 'doctor-1',
    email: 'dr.chen@mediqueue.com',
    role: 'doctor',
    full_name: 'Dr. Michael Chen',
    phone: '+1 (555) 100-2001',
    avatar_url: null,
    created_at: '2023-06-01T08:00:00Z',
  },
  doctor2: {
    id: 'doctor-user-2',
    doctor_id: 'doctor-2',
    email: 'dr.patel@mediqueue.com',
    role: 'doctor',
    full_name: 'Dr. Priya Patel',
    phone: '+1 (555) 100-2002',
    avatar_url: null,
    created_at: '2023-06-01T08:00:00Z',
  },
  mediator1: {
    id: 'mediator-user-1',
    email: 'admin@mediqueue.com',
    role: 'mediator',
    full_name: 'James Wilson',
    phone: '+1 (555) 100-0001',
    avatar_url: null,
    created_at: '2023-01-01T08:00:00Z',
  },
}

// ─── DEMO CREDENTIALS ────────────────────────────────────────────────────────
export const DEMO_CREDENTIALS = [
  { role: 'patient', email: 'sarah.johnson@email.com', password: 'demo1234', label: 'Patient' },
  { role: 'doctor', email: 'dr.chen@mediqueue.com', password: 'demo1234', label: 'Doctor' },
  { role: 'mediator', email: 'admin@mediqueue.com', password: 'demo1234', label: 'Mediator' },
]

// ─── DOCTORS ─────────────────────────────────────────────────────────────────
export const MOCK_DOCTORS = [
  {
    id: 'doctor-1',
    user_id: 'doctor-user-1',
    user: { full_name: 'Dr. Michael Chen', email: 'dr.chen@mediqueue.com', phone: '+1 (555) 100-2001' },
    specialization: 'Cardiology',
    license_number: 'MD-2019-4521',
    department: 'Heart & Vascular',
    consultation_avg_time: 18,
    experience_years: 12,
    rating: 4.8,
    bio: 'Board-certified cardiologist with 12 years of experience in interventional cardiology and heart failure management.',
    availability_schedule: {
      monday: { start: '09:00', end: '17:00', slots: 20 },
      tuesday: { start: '09:00', end: '17:00', slots: 20 },
      wednesday: { start: '09:00', end: '13:00', slots: 10 },
      thursday: { start: '09:00', end: '17:00', slots: 20 },
      friday: { start: '09:00', end: '16:00', slots: 18 },
    },
    is_available: true,
    patients_today: 14,
  },
  {
    id: 'doctor-2',
    user_id: 'doctor-user-2',
    user: { full_name: 'Dr. Priya Patel', email: 'dr.patel@mediqueue.com', phone: '+1 (555) 100-2002' },
    specialization: 'Cardiology',
    license_number: 'MD-2020-7832',
    department: 'Heart & Vascular',
    consultation_avg_time: 15,
    experience_years: 8,
    rating: 4.6,
    bio: 'Specialist in echocardiography and non-invasive cardiac imaging with extensive research background.',
    availability_schedule: {
      monday: { start: '10:00', end: '18:00', slots: 18 },
      tuesday: { start: '10:00', end: '18:00', slots: 18 },
      thursday: { start: '10:00', end: '18:00', slots: 18 },
      friday: { start: '10:00', end: '15:00', slots: 12 },
    },
    is_available: true,
    patients_today: 9,
  },
  {
    id: 'doctor-3',
    user_id: 'doctor-user-3',
    user: { full_name: 'Dr. Emily Roberts', email: 'dr.roberts@mediqueue.com', phone: '+1 (555) 100-2003' },
    specialization: 'General Medicine',
    license_number: 'MD-2018-3301',
    department: 'General OPD',
    consultation_avg_time: 12,
    experience_years: 15,
    rating: 4.9,
    bio: 'Experienced general physician specializing in preventive care and chronic disease management.',
    availability_schedule: {
      monday: { start: '08:00', end: '16:00', slots: 24 },
      tuesday: { start: '08:00', end: '16:00', slots: 24 },
      wednesday: { start: '08:00', end: '16:00', slots: 24 },
      thursday: { start: '08:00', end: '16:00', slots: 24 },
      friday: { start: '08:00', end: '14:00', slots: 16 },
    },
    is_available: true,
    patients_today: 21,
  },
  {
    id: 'doctor-4',
    user_id: 'doctor-user-4',
    user: { full_name: 'Dr. Ahmed Hassan', email: 'dr.hassan@mediqueue.com', phone: '+1 (555) 100-2004' },
    specialization: 'Orthopedics',
    license_number: 'MD-2017-5698',
    department: 'Bone & Joint',
    consultation_avg_time: 20,
    experience_years: 18,
    rating: 4.7,
    bio: 'Orthopedic surgeon specializing in joint replacement and sports medicine.',
    availability_schedule: {
      monday: { start: '09:00', end: '17:00', slots: 16 },
      wednesday: { start: '09:00', end: '17:00', slots: 16 },
      friday: { start: '09:00', end: '15:00', slots: 12 },
    },
    is_available: false,
    patients_today: 8,
  },
]

// ─── PATIENTS ─────────────────────────────────────────────────────────────────
export const MOCK_PATIENTS = [
  {
    id: 'patient-1',
    user_id: 'patient-user-1',
    user: { full_name: 'Sarah Johnson', email: 'sarah.johnson@email.com', phone: '+1 (555) 234-5678' },
    date_of_birth: '1990-03-15',
    blood_type: 'O+',
    allergies: ['Penicillin', 'Shellfish'],
    medical_history: ['Hypertension', 'Asthma'],
    emergency_contact: { name: 'John Johnson', phone: '+1 (555) 234-5679', relation: 'Spouse' },
    insurance_info: { provider: 'BlueCross', policy_number: 'BC-2024-98765' },
  },
  {
    id: 'patient-2',
    user_id: 'patient-user-2',
    user: { full_name: 'Robert Martinez', email: 'r.martinez@email.com', phone: '+1 (555) 345-6789' },
    date_of_birth: '1975-08-22',
    blood_type: 'A+',
    allergies: [],
    medical_history: ['Type 2 Diabetes', 'High Cholesterol'],
    emergency_contact: { name: 'Maria Martinez', phone: '+1 (555) 345-6780', relation: 'Wife' },
    insurance_info: { provider: 'Aetna', policy_number: 'AE-2024-12345' },
  },
  {
    id: 'patient-3',
    user_id: 'patient-user-3',
    user: { full_name: 'Linda Thompson', email: 'l.thompson@email.com', phone: '+1 (555) 456-7890' },
    date_of_birth: '1985-11-30',
    blood_type: 'B-',
    allergies: ['Latex', 'Aspirin'],
    medical_history: [],
    emergency_contact: { name: 'Tom Thompson', phone: '+1 (555) 456-7891', relation: 'Husband' },
    insurance_info: { provider: 'United Health', policy_number: 'UH-2024-54321' },
  },
]

// ─── APPOINTMENTS ─────────────────────────────────────────────────────────────
export const MOCK_APPOINTMENTS = [
  {
    id: 'appt-1',
    patient_id: 'patient-user-1',
    doctor_id: 'doctor-1',
    patient: MOCK_PATIENTS[0],
    doctor: MOCK_DOCTORS[0],
    scheduled_time: format(addMinutes(now, 30), "yyyy-MM-dd'T'HH:mm:ss"),
    visit_type: 'follow_up',
    symptoms: 'Chest pain follow-up, shortness of breath',
    status: 'confirmed',
    notes: 'Patient reported improvement with medication.',
    created_at: subMinutes(now, 1440).toISOString(),
  },
  {
    id: 'appt-2',
    patient_id: 'patient-user-2',
    doctor_id: 'doctor-1',
    patient: MOCK_PATIENTS[1],
    doctor: MOCK_DOCTORS[0],
    scheduled_time: format(addMinutes(now, 75), "yyyy-MM-dd'T'HH:mm:ss"),
    visit_type: 'first_visit',
    symptoms: 'Palpitations, dizziness',
    status: 'confirmed',
    notes: '',
    created_at: subMinutes(now, 2880).toISOString(),
  },
  {
    id: 'appt-3',
    patient_id: 'patient-user-3',
    doctor_id: 'doctor-1',
    patient: MOCK_PATIENTS[2],
    doctor: MOCK_DOCTORS[0],
    scheduled_time: format(addMinutes(now, 120), "yyyy-MM-dd'T'HH:mm:ss"),
    visit_type: 'follow_up',
    symptoms: 'Blood pressure monitoring',
    status: 'pending',
    notes: '',
    created_at: subMinutes(now, 720).toISOString(),
  },
  {
    id: 'appt-4',
    patient_id: 'patient-user-1',
    doctor_id: 'doctor-3',
    patient: MOCK_PATIENTS[0],
    doctor: MOCK_DOCTORS[2],
    scheduled_time: format(subMinutes(now, 2400), "yyyy-MM-dd'T'HH:mm:ss"),
    visit_type: 'first_visit',
    symptoms: 'Annual checkup',
    status: 'completed',
    notes: 'All vitals normal. Continue current medications.',
    created_at: subMinutes(now, 5760).toISOString(),
  },
]

// ─── QUEUE ENTRIES ────────────────────────────────────────────────────────────
export const MOCK_QUEUE = [
  {
    id: 'q-1',
    doctor_id: 'doctor-1',
    patient_id: 'patient-user-3',
    appointment_id: null,
    queue_type: 'in_consultation',
    token_number: 'T-001',
    priority_score: 200,
    predicted_consultation_time: 15,
    status: 'in_consultation',
    check_in_status: true,
    check_in_time: subMinutes(now, 5).toISOString(),
    called_at: subMinutes(now, 2).toISOString(),
    completed_at: null,
    created_at: subMinutes(now, 60).toISOString(),
    patient: { full_name: 'Linda Thompson', phone: '+1 (555) 456-7890' },
    doctor: MOCK_DOCTORS[0],
  },
  {
    id: 'q-2',
    doctor_id: 'doctor-1',
    patient_id: 'patient-user-1',
    appointment_id: 'appt-1',
    queue_type: 'appointment',
    token_number: 'T-002',
    priority_score: 175,
    predicted_consultation_time: 18,
    status: 'waiting',
    check_in_status: true,
    check_in_time: subMinutes(now, 15).toISOString(),
    called_at: null,
    completed_at: null,
    created_at: subMinutes(now, 90).toISOString(),
    patient: { full_name: 'Sarah Johnson', phone: '+1 (555) 234-5678' },
    doctor: MOCK_DOCTORS[0],
  },
  {
    id: 'q-3',
    doctor_id: 'doctor-1',
    patient_id: 'patient-user-2',
    appointment_id: 'appt-2',
    queue_type: 'appointment',
    token_number: 'T-003',
    priority_score: 140,
    predicted_consultation_time: 25,
    status: 'waiting',
    check_in_status: false,
    check_in_time: null,
    called_at: null,
    completed_at: null,
    created_at: subMinutes(now, 45).toISOString(),
    patient: { full_name: 'Robert Martinez', phone: '+1 (555) 345-6789' },
    doctor: MOCK_DOCTORS[0],
  },
  {
    id: 'q-4',
    doctor_id: 'doctor-1',
    patient_id: 'walk-in-1',
    appointment_id: null,
    queue_type: 'walk_in',
    token_number: 'W-004',
    priority_score: 110,
    predicted_consultation_time: 12,
    status: 'waiting',
    check_in_status: true,
    check_in_time: subMinutes(now, 20).toISOString(),
    called_at: null,
    completed_at: null,
    created_at: subMinutes(now, 30).toISOString(),
    patient: { full_name: 'James Park', phone: '+1 (555) 567-8901' },
    doctor: MOCK_DOCTORS[0],
  },
  {
    id: 'q-5',
    doctor_id: 'doctor-1',
    patient_id: 'emergency-1',
    appointment_id: null,
    queue_type: 'emergency',
    token_number: 'E-005',
    priority_score: 650,
    predicted_consultation_time: 30,
    status: 'waiting',
    check_in_status: true,
    check_in_time: subMinutes(now, 8).toISOString(),
    called_at: null,
    completed_at: null,
    created_at: subMinutes(now, 8).toISOString(),
    patient: { full_name: 'Maria Garcia', phone: '+1 (555) 678-9012' },
    doctor: MOCK_DOCTORS[0],
  },
]

// ─── MEDICAL RECORDS ─────────────────────────────────────────────────────────
export const MOCK_MEDICAL_RECORDS = [
  {
    id: 'rec-1',
    patient_id: 'patient-1',
    doctor_id: 'doctor-3',
    appointment_id: 'appt-4',
    doctor: MOCK_DOCTORS[2],
    diagnosis: 'Hypertension - Stage 1',
    prescription: [
      { name: 'Lisinopril', dosage: '10mg', frequency: 'Once daily', duration: '30 days' },
      { name: 'Amlodipine', dosage: '5mg', frequency: 'Once daily', duration: '30 days' },
    ],
    notes: 'Patient blood pressure 145/92. Started antihypertensive therapy. Follow up in 4 weeks.',
    attachments: [],
    created_at: subMinutes(now, 2400).toISOString(),
  },
  {
    id: 'rec-2',
    patient_id: 'patient-1',
    doctor_id: 'doctor-1',
    appointment_id: null,
    doctor: MOCK_DOCTORS[0],
    diagnosis: 'Atrial Fibrillation - Paroxysmal',
    prescription: [
      { name: 'Metoprolol', dosage: '25mg', frequency: 'Twice daily', duration: '90 days' },
      { name: 'Apixaban', dosage: '5mg', frequency: 'Twice daily', duration: '90 days' },
    ],
    notes: 'ECG confirmed paroxysmal AF. Initiated rate control and anticoagulation.',
    attachments: [],
    created_at: subMinutes(now, 720).toISOString(),
  },
]

// ─── NOTIFICATIONS ────────────────────────────────────────────────────────────
export const MOCK_NOTIFICATIONS = [
  {
    id: 'notif-1',
    user_id: 'patient-user-1',
    title: 'Appointment Confirmed',
    message: 'Your appointment with Dr. Michael Chen is confirmed for today.',
    type: 'appointment',
    read: false,
    data: { appointment_id: 'appt-1' },
    created_at: subMinutes(now, 240).toISOString(),
  },
  {
    id: 'notif-2',
    user_id: 'patient-user-1',
    title: 'Queue Update',
    message: 'You are now #2 in the queue. Estimated wait: 15 minutes.',
    type: 'queue',
    read: false,
    data: { queue_id: 'q-2', position: 2 },
    created_at: subMinutes(now, 5).toISOString(),
  },
  {
    id: 'notif-3',
    user_id: 'patient-user-1',
    title: 'Medical Record Added',
    message: 'Dr. Emily Roberts added a new prescription to your records.',
    type: 'medical',
    read: true,
    data: { record_id: 'rec-1' },
    created_at: subMinutes(now, 2400).toISOString(),
  },
]

// ─── MESSAGES ─────────────────────────────────────────────────────────────────
export const MOCK_MESSAGES = [
  {
    id: 'msg-1',
    sender_id: 'patient-user-1',
    receiver_id: 'doctor-user-1',
    content: 'Dr. Chen, I wanted to follow up on my medication. I\'ve been experiencing some dizziness in the mornings.',
    read: true,
    created_at: subMinutes(now, 300).toISOString(),
    sender: MOCK_USERS.patient1,
  },
  {
    id: 'msg-2',
    sender_id: 'doctor-user-1',
    receiver_id: 'patient-user-1',
    content: 'Hello Sarah, the dizziness may be due to the Amlodipine. Try taking it in the evening instead. If it persists, come in for a check.',
    read: true,
    created_at: subMinutes(now, 260).toISOString(),
    sender: MOCK_USERS.doctor1,
  },
  {
    id: 'msg-3',
    sender_id: 'patient-user-1',
    receiver_id: 'doctor-user-1',
    content: 'Thank you! I\'ll try that. Should I monitor my blood pressure more frequently?',
    read: false,
    created_at: subMinutes(now, 120).toISOString(),
    sender: MOCK_USERS.patient1,
  },
]

// ─── HOSPITAL STATS ───────────────────────────────────────────────────────────
export const MOCK_HOSPITAL_STATS = {
  total_patients_today: 87,
  appointments_today: 64,
  walk_ins_today: 23,
  completed_consultations: 52,
  avg_wait_time: 22,
  patient_satisfaction: 4.6,
  active_doctors: 6,
  pending_queue_count: 35,
  emergency_cases: 3,
}

// ─── FAMILY MEMBERS ───────────────────────────────────────────────────────────
export const MOCK_FAMILY_MEMBERS = [
  {
    id: 'fam-1',
    patient_id: 'patient-1',
    name: 'Emma Johnson',
    relationship: 'daughter',
    date_of_birth: '2018-06-10',
    blood_type: 'O+',
    notes: 'Has mild asthma, uses inhaler as needed.',
  },
]
